name: "OpenMapTiles"

maps:
  domain: "https://api.maptiler.com"
  key: "egrA25FNSYcFuvl6Lb8Y"

permalink: pretty

sass:
  style: :compressed
  sass_dir: styles/_sass

exclude:
- "styles/*"

plugins:
- jekyll-redirect-from
